#!/bin/bash

# OAuth Setup Script for Render.com
# This script helps you configure all OAuth credentials on Render

echo "🚀 OAuth Setup Helper for Render.com"
echo "===================================="
echo ""
echo "This script will guide you through adding OAuth credentials to your Render API service."
echo ""

# Check if render CLI is installed
if ! command -v render &> /dev/null; then
    echo "⚠️  Render CLI not found. You'll need to add environment variables manually."
    echo ""
    echo "Go to: https://dashboard.render.com/"
    echo "1. Find your 'autorepost-api' service"
    echo "2. Click 'Environment' in the left sidebar"
    echo "3. Add the variables shown below"
    echo ""
fi

echo "📋 Required OAuth Environment Variables"
echo "========================================"
echo ""

echo "🐦 TWITTER/X OAuth"
echo "----------------------------------------"
echo "Get credentials from: https://developer.twitter.com/en/portal/dashboard"
echo ""
echo "Required variables:"
echo "  TWITTER_CONSUMER_KEY=<your Twitter API Key>"
echo "  TWITTER_CONSUMER_SECRET=<your Twitter API Secret>"
echo "  TWITTER_CALLBACK_URL=https://autorepost-api-l4oy.onrender.com/api/oauth/twitter/callback"
echo ""
read -p "Press Enter when you have these credentials ready..."
echo ""

echo "▶️ YOUTUBE OAuth"
echo "----------------------------------------"
echo "Get credentials from: https://console.cloud.google.com/"
echo ""
echo "Required variables:"
echo "  YOUTUBE_CLIENT_ID=<your Google OAuth Client ID>"
echo "  YOUTUBE_CLIENT_SECRET=<your Google OAuth Client Secret>"
echo "  YOUTUBE_CALLBACK_URL=https://autorepost-api-l4oy.onrender.com/api/oauth/youtube/callback"
echo ""
read -p "Press Enter when you have these credentials ready..."
echo ""

echo "📸 INSTAGRAM OAuth"
echo "----------------------------------------"
echo "Get credentials from: https://developers.facebook.com/apps/"
echo ""
echo "Required variables:"
echo "  INSTAGRAM_CLIENT_ID=<your Instagram App ID>"
echo "  INSTAGRAM_CLIENT_SECRET=<your Instagram App Secret>"
echo "  INSTAGRAM_CALLBACK_URL=https://autorepost-api-l4oy.onrender.com/api/oauth/instagram/callback"
echo ""
read -p "Press Enter when you have these credentials ready..."
echo ""

echo "✅ NEXT STEPS"
echo "========================================"
echo ""
echo "1. Go to: https://dashboard.render.com/"
echo "2. Click on your 'autorepost-api' service"
echo "3. Click 'Environment' in the sidebar"
echo "4. Click 'Add Environment Variable' for each:"
echo ""
echo "   Twitter:"
echo "   - TWITTER_CONSUMER_KEY"
echo "   - TWITTER_CONSUMER_SECRET"
echo "   - TWITTER_CALLBACK_URL"
echo ""
echo "   YouTube:"
echo "   - YOUTUBE_CLIENT_ID"
echo "   - YOUTUBE_CLIENT_SECRET"
echo "   - YOUTUBE_CALLBACK_URL"
echo ""
echo "   Instagram:"
echo "   - INSTAGRAM_CLIENT_ID"
echo "   - INSTAGRAM_CLIENT_SECRET"
echo "   - INSTAGRAM_CALLBACK_URL"
echo ""
echo "5. Click 'Save Changes' - this will trigger a redeploy (~5 minutes)"
echo ""
echo "6. After redeploy completes, test connections at:"
echo "   https://autorepost-web.onrender.com/console/connections"
echo ""
echo "🎉 Done! Your OAuth should work after the redeploy completes."
